[project]
name = "hacker-news-clone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.4",
]

[dependency-groups]
dev = [
    "behave>=1.2.6",
    "behave-django>=1.4.0",
]
