# Generated by Django 5.1.4 on 2024-12-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
